export interface Pattern {
  id: string;
  topic: string;
  /** Original global agenda line (English). */
  globalText: string;
  /**
   * Machine-translated Korean of `globalText` (editor-provided; for comparing wording to Korean policy text).
   * Not an official translation of any institution.
   */
  globalTextKo: string;
  /** Korean-side mirror / official-style summary (Korean). */
  koreanText: string;
  agendaTags: string[];
  relatedKeywords: string[];
  /** Editorial / political search terms — lower weight in Fuse; shown with a badge when they drive a hit. */
  searchAliases?: string[];
  globalSource: string;
  koreanSource: string;
  /** Short Korean label for the Korean primary link (e.g. 한국은행 디지털화폐 안내). */
  koreanSourceLabelKo: string;
  date: string;
  similarityHint: string;
  sourceVerified: boolean;
}

/** Curated dataset — expand via Research Station CSV import/export. */
export const patterns: Pattern[] = [
  {
    id: 'cbdc-1',
    topic: 'CBDC / Digital Currency',
    globalText:
      'BIS and Atlantic Council track Central Bank Digital Currency pilots for retail and tokenized deposits.',
    globalTextKo:
      'BIS와 애틀랜틱 카운슬은 소매 결제와 토큰화된 예금을 위한 중앙은행 디지털화폐(CBDC) 시범사업을 추적한다.',
    koreanText:
      '한국은행 「프로젝트 한강」: 소매 시범(2025.4~6), 예금토큰·프로그래밍 가능 바우처 등(세부는 한국은행 공개 자료 기준).',
    agendaTags: ['BIS'],
    relatedKeywords: [
      'CBDC',
      'central bank digital currency',
      'digital currency',
      'digital won',
      'e-won',
      'digital KRW',
      'deposit token',
      'tokenized deposit',
      'programmable money',
      'programmable',
      'retail CBDC',
      'wholesale CBDC',
      'digital control',
      'subsidy',
      'BIS pilot',
      '디지털화폐',
      '디지털원화',
      '한강프로젝트',
      '한강',
      '한국은행',
      '예금토큰',
      '프로그래밍화폐',
      'global coordination',
      'EU digital euro',
      'cross-border CBDC',
      'BIS coordination',
      'financial surveillance',
      '글로벌 금융',
    ],
    globalSource: 'https://www.atlanticcouncil.org/cbdctracker/',
    koreanSource: 'https://www.bok.or.kr/portal/submain/submain/cbdc.do?menuNo=201136',
    koreanSourceLabelKo: '한국은행 디지털화폐(프로젝트 한강) 안내',
    date: '2020 global push → 2025.4–6 Phase 1 pilot',
    similarityHint: 'policy implementation',
    sourceVerified: true,
  },
  {
    id: 'ai-1',
    topic: 'AI Misinformation Laws',
    globalText:
      'EU AI Act and global forums emphasize labeling and transparency for AI-generated content.',
    globalTextKo:
      'EU AI법과 국제 포럼은 AI 생성 콘텐츠에 대한 라벨링과 투명성을 강조한다.',
    koreanText:
      '「인공지능 기본법」(법제처): 라벨링 의무·시행일·과태료 등은 공포문·조문을 기준으로 확인.',
    agendaTags: ['WEF', 'UN'],
    relatedKeywords: [
      'misinformation',
      'disinformation',
      'deepfake',
      'fake content',
      'synthetic media',
      'AI-generated content',
      'labeling',
      'watermark',
      'content authenticity',
      'transparency',
      'AI regulation',
      'AI Act',
      'AI law',
      '인공지능',
      '인공지능기본법',
      'AI기본법',
      '허위조작정보',
      '딥페이크',
      '라벨링',
      '워터마크',
      'fake news',
      'fake news law',
      'fake news suppression',
      'disinformation law',
      'platform censorship',
      'speech crime',
      '가짜뉴스',
      '언론탄압',
    ],
    searchAliases: [
      'judicial harassment',
      'Brazil',
      'Brasil',
      'Korea Brazil parallel',
      'Latin America',
      'EU DSA',
      'EU influence',
      'Open Society',
      'Soros',
      'foreign-funded NGO',
    ],
    globalSource:
      'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32024R1689',
    koreanSource: 'https://www.law.go.kr/lsInfoP.do?lsId=014820',
    koreanSourceLabelKo: '국가법령정보센터 · 인공지능기본법',
    date: '2024 passage → 2026.01.22 enforcement (verify on law.go.kr)',
    similarityHint: 'regulatory mirror',
    sourceVerified: true,
  },
  {
    id: 'covid-1',
    topic: 'COVID Policy Response',
    globalText: 'WHO PHEIC (2020) and international coordination on health emergencies.',
    globalTextKo:
      'WHO는 2020년 국제적 공중보건 비상사태(PHEIC)를 선언하고, 보건 비상사태에 대한 국제적 조정을 촉진했다.',
    koreanText:
      '감염병 위기관보·대응 체계(질병관리청 등): 구체 일자·단계는 KDCA·당시 공식 보도·지침을 기준으로 확인.',
    agendaTags: ['WHO'],
    relatedKeywords: [
      'pandemic',
      'COVID',
      'COVID-19',
      'coronavirus',
      'epidemic',
      'outbreak',
      'health emergency',
      'PHEIC',
      'quarantine',
      'lockdown',
      'contact tracing',
      'vaccination',
      'KDCA',
      '감염병',
      '코로나',
      '코로나19',
      '방역',
      '격리',
      '위기경보',
      '질병관리청',
      'infodemic',
      'health misinformation',
      'misinformation narrative',
      'WHO coordination',
      'pandemic narrative',
    ],
    globalSource: 'https://www.who.int/',
    koreanSource: 'https://www.kdca.go.kr/',
    koreanSourceLabelKo: '질병관리청(KDCA)',
    date: '2020.01 WHO PHEIC → Korea parallel response',
    similarityHint: 'rapid diffusion',
    sourceVerified: true,
  },
  {
    id: 'digitalid-1',
    topic: 'Digital ID / DPI',
    globalText: 'Global DPI narratives include digital identity and wallet-style credentials.',
    globalTextKo:
      '글로벌 DPI 담론에는 디지털 신원과 지갑형 자격 증명이 포함된다.',
    koreanText:
      '모바일 운전면허증·PASS 등 디지털 신원·전자정부 서비스(세부는 행정안전부·공식 공지 기준).',
    agendaTags: ['WEF', 'World Bank'],
    relatedKeywords: [
      'digital ID',
      'digital identity',
      'mobile ID',
      'e-ID',
      'national ID',
      'identity wallet',
      'digital wallet',
      'verifiable credential',
      'biometric',
      'PASS',
      'DPI',
      'digital public infrastructure',
      '디지털신분증',
      '전자신분증',
      '모바일 운전면허증',
      '인증',
      '공인인증서',
      '행정안전부',
      'eIDAS',
      'digital control grid',
      'credential surveillance',
      'EU digital identity',
    ],
    searchAliases: ['digital control grid', 'credential surveillance', 'wallet surveillance'],
    globalSource:
      'https://www.worldbank.org/ext/en/topic/digital-and-ai/digital-public-infrastructure-and-services',
    koreanSource: 'https://www.mois.go.kr/',
    koreanSourceLabelKo: '행정안전부(전자정부·신분·민원)',
    date: '2016–2022+ Korea digital ID rollout',
    similarityHint: 'identity infrastructure',
    sourceVerified: true,
  },
  {
    id: 'esg-1',
    topic: 'ESG / Climate Disclosure',
    globalText: 'Paris Agreement and ISSB-style climate disclosure momentum.',
    globalTextKo:
      '파리협정과 ISSB 스타일의 기후 관련 공시 흐름이 있다.',
    koreanText:
      '탄소중립·녹색성장·기후 공시 관련 국내 법령·금융당국 로드맵(법제처·금융위·금감원 자료 확인).',
    agendaTags: ['UN'],
    relatedKeywords: [
      'ESG',
      'net zero',
      'carbon',
      'carbon neutral',
      'carbon neutrality',
      'climate',
      'climate disclosure',
      'sustainability',
      'sustainable finance',
      'green finance',
      'GHG',
      'greenhouse gas',
      'scope 3',
      'ISSB',
      'TCFD',
      'NDC',
      '탄소중립',
      '기후변화',
      '지속가능성',
      '온실가스',
      '녹색금융',
      '공시',
      'EU Green Deal',
      'EU taxonomy',
      'global governance',
      'climate diplomacy',
    ],
    searchAliases: ['NGO pressure', 'foreign climate finance'],
    globalSource: 'https://unfccc.int/process-and-meetings/the-paris-agreement',
    koreanSource: 'https://www.law.go.kr/',
    koreanSourceLabelKo: '국가법령정보센터(기후·탄소중립 관련 법령 검색)',
    date: '2015 Paris → 2020+ Korea NDC / legislation',
    similarityHint: 'commitment → legislation',
    sourceVerified: true,
  },
  {
    id: 'detention-1',
    topic: 'Immigration Detention / GCR',
    globalText:
      'GCR (nonbinding) and UNHCR detention guidance emphasize last resort and alternatives to detention.',
    globalTextKo:
      'GCR(비구속)과 UNHCR 구금 지침은 최후의 수단과 구금 대안을 강조한다.',
    koreanText:
      '「출입국관리법」 제63조 등에 대한 헌법재판소 결정 및 국회 입법·정부 시행(공문·헌재·국회 자료 기준).',
    agendaTags: ['UN', 'UNHCR'],
    relatedKeywords: [
      'GCR',
      'Global Compact on Refugees',
      'detention',
      'immigration detention',
      'alternatives to detention',
      'ATD',
      'asylum',
      'asylum seeker',
      'refugee',
      'migrant',
      'deportation',
      'immigration',
      'undocumented',
      'UNHCR',
      '출입국',
      '난민',
      '이민자',
      '구금',
      '외국인보호소',
      '비자',
      '체류',
      'judicial self-investigation',
      'rule of law',
      'court independence',
      'UNHCR pressure',
      'GCR implementation',
      '사법 독립',
    ],
    searchAliases: ['Brazil migration', 'Latin America asylum', 'Open Society', 'Soros', 'foreign NGO'],
    globalSource: 'https://www.unhcr.org/international/global-compact-refugees',
    koreanSource: 'https://www.ccourt.go.kr/',
    koreanSourceLabelKo: '헌법재판소',
    date: '2018 GCR → 2023 court → legislative process',
    similarityHint: 'soft law + litigation channel',
    sourceVerified: true,
  },
  {
    id: 'pandemic-sim-1',
    topic: 'Pandemic Preparedness Simulation',
    globalText:
      'CEPI “100 Days Mission” tabletop exercises and WHO-aligned preparedness drills stress rapid vaccine R&D and whole-of-government coordination for novel pathogens.',
    globalTextKo:
      'CEPI의 ‘100일 미션’ 토론형 연습과 WHO 계열의 대비 훈련은 신종 병원체에 대한 신속 백신 R&D와 정부 전체 조정을 강조한다.',
    koreanText:
      '질병관리청·식약처 등과 CEPI·IVI가 참여하는 가상 팬데믹 테이블톱(모의훈련) 등: 세부 일정·보도는 KDCA·CEPI 공개 자료 기준으로 확인.',
    agendaTags: ['WHO', 'WEF'],
    relatedKeywords: [
      'pandemic simulation',
      'tabletop exercise',
      'CEPI',
      '100 Days Mission',
      'Gates Foundation',
      'vaccine R&D',
      'outbreak readiness',
      'KDCA',
      'IVI',
      'health security',
      'next pandemic',
      '시뮬레이션',
      '백신',
      '팬데믹',
      '질병관리청',
      '방역 훈련',
    ],
    searchAliases: ['Gates Foundation'],
    globalSource: 'https://cepi.net/korea-runs-landmark-pandemic-simulation-exercise-strengthen-outbreak-readiness',
    koreanSource: 'https://www.kdca.go.kr/',
    koreanSourceLabelKo: '질병관리청(KDCA)',
    date: '2026.02 CEPI–Korea–IVI tabletop (Seoul; per CEPI release) → broader preparedness ongoing',
    similarityHint: 'drill → institutional alignment',
    sourceVerified: true,
  },
  {
    id: 'esg-finance-1',
    topic: 'ESG Disclosure & Green Finance (Banks)',
    globalText:
      'ISSB/TCFD-style sustainability disclosure and ESG ratings increasingly bind banks and issuers in major economies.',
    globalTextKo:
      'ISSB·TCFD 스타일의 지속가능성 공시와 ESG 평가가 주요국 은행·발행사에 점점 더 구속력 있게 작동한다.',
    koreanText:
      '금융위·금감원 ESG·기후 공시 로드맵, 녹색채권·지속가능채 등(은행 공시·등급은 각사 IR·감독 자료 기준).',
    agendaTags: ['UN', 'BIS'],
    relatedKeywords: [
      'ESG rating',
      'sustainable finance',
      'green bond',
      'TCFD',
      'ISSB',
      'bank disclosure',
      'AAA ESG',
      'climate risk',
      '금융공시',
      '녹색금융',
      'ESG 채권',
      '금융위',
      '금감원',
      '기후 공시',
    ],
    globalSource: 'https://www.ifrs.org/issued-standards/list-of-standards/',
    koreanSource: 'https://www.fsc.go.kr/',
    koreanSourceLabelKo: '금융위원회',
    date: '2020+ global ISSB momentum → Korea FSC roadmap',
    similarityHint: 'disclosure convergence',
    sourceVerified: true,
  },
  {
    id: 'fake-news-1',
    topic: 'Fake News Suppression Laws',
    globalText:
      'Governments invoke “fake news” and information-offence laws in similar ways across jurisdictions; civil society tracks parallel judicial and enforcement patterns.',
    globalTextKo:
      '여러 국가 정부가 ‘가짜 뉴스’·정보 관련 법령을 유사한 방식으로 적용하고, 시민사회는 재판·집행의 평행 패턴을 추적한다.',
    koreanText:
      '「인공지능 기본법」의 허위조작정보 조항, 형법·언론 관련 논의 등(구체 적용은 판례·법제처·언론 보도 확인). AI 전용 행(ai-1)과 인접.',
    agendaTags: ['UN', 'WEF'],
    relatedKeywords: [
      'fake news',
      'fake news law',
      'disinformation',
      'speech offence',
      'platform liability',
      'judicial pattern',
      'Brazil Korea',
      '가짜뉴스',
      '허위조작정보',
      '언론탄압',
      '표현의 자유',
    ],
    globalSource: 'https://www.ohchr.org/en/freedom-of-expression',
    koreanSource: 'https://www.law.go.kr/lsInfoP.do?lsId=014820',
    koreanSourceLabelKo: '국가법령정보센터 · 인공지능기본법(허위조작정보)',
    date: '2020+ global statutes → 2026.01.22 KR AI Act',
    similarityHint: 'cross-country terminology',
    sourceVerified: true,
  },
  {
    id: 'healthcare-1',
    topic: 'Universal Healthcare / NHIS Model',
    globalText:
      'National health insurance models (e.g. Bismarck/SHI lineage) are compared internationally; Korea’s single-payer NHIS is often discussed alongside US Medicare analogies in policy literature.',
    globalTextKo:
      '국민건강보험(사회보험) 모델은 국제 비교 대상이며, 한국의 단일공급자 NHIS는 정책 문헌에서 미국 메디케어와의 비유가 나오기도 한다.',
    koreanText:
      '국민건강보험공단·보건복지부 관할 보장체계(보장 범위·재원은 공단·공식 통계 기준). “메디케어 복제” 주장은 학술·논쟁 수준 — 단정적 주장은 출처 확인 필요.',
    agendaTags: ['WHO', 'World Bank'],
    relatedKeywords: [
      'NHIS',
      'National Health Insurance',
      'single payer',
      'Medicare',
      'universal coverage',
      'health financing',
      'Korea healthcare',
      '국민건강보험',
      '건강보험',
      '보건복지부',
      '의료보장',
    ],
    globalSource: 'https://www.who.int/health-topics/universal-health-coverage',
    koreanSource: 'https://www.nhis.or.kr/',
    koreanSourceLabelKo: '국민건강보험공단',
    date: '1989 NHIS founding → 2020+ reform debates',
    similarityHint: 'model comparison discourse',
    sourceVerified: true,
  },
  {
    id: 'soft-power-1',
    topic: 'Soft Power & Cultural Export (K-content)',
    globalText:
      'States deliberately promote audiovisual industries and cultural exports as strategic assets (OECD / industry policy discourse).',
    globalTextKo:
      '국가는 시청각 산업·문화 수출을 전략 자산으로 육성한다(OECD·산업정책 담론).',
    koreanText:
      '문화체육관광부 K-콘텐츠·해외 진흥 정책, 한류 관련 지원·통계(세부는 공식 사업 공고 기준). “일본 아이돌 모방” 등은 대중 담론 — 학술 검증은 별도.',
    agendaTags: ['UN'],
    relatedKeywords: [
      'soft power',
      'K-pop',
      'K-drama',
      'Hallyu',
      'cultural export',
      'creative industries',
      'MCST',
      '한류',
      'K-콘텐츠',
      '문화체육관광부',
      '문화산업',
    ],
    globalSource: 'https://www.mcst.go.kr/',
    koreanSource: 'https://www.mcst.go.kr/',
    koreanSourceLabelKo: '문화체육관광부',
    date: '2000+ K-content push → 2020+ global expansion',
    similarityHint: 'strategic culture industry',
    sourceVerified: true,
  },
  {
    id: 'cbdc-stablecoin-1',
    topic: 'CBDC + Stablecoin Ecosystem',
    globalText:
      'Central banks pilot CBDC while regulators debate coexistence with bank-issued or fiat-pegged stablecoins — “multi-money” narratives.',
    globalTextKo:
      '중앙은행은 CBDC를 시범하면서 은행 발행·법정화페 연동 스테이블코인과의 공존을 규제 논의한다 — ‘멀티 머니’ 서사.',
    koreanText:
      '한국은행 프로젝트 한강(도매·예금토큰)·원화 스테이블코인 입법 논의(금융위·국회 안, 2025–2026 보도·청문 자료 확인).',
    agendaTags: ['BIS'],
    relatedKeywords: [
      'stablecoin',
      'won stablecoin',
      'deposit token',
      'multi-money',
      'CBDC coexistence',
      'Project Hangang',
      'BOK',
      '스테이블코인',
      '디지털자산',
      '예금토큰',
      '한국은행',
      '멀티 머니버스',
    ],
    globalSource: 'https://www.bis.org/about/bisih/topics/cbdc.htm',
    koreanSource: 'https://www.bok.or.kr/',
    koreanSourceLabelKo: '한국은행',
    date: '2024–2026 BOK-FSC stablecoin framing + Hangang',
    similarityHint: 'dual-track digital money',
    sourceVerified: true,
  },
  {
    id: 'state-planning-1',
    topic: 'State-Led Development & Banking',
    globalText:
      'Development-state literature contrasts dirigiste credit allocation and industrial policy with Washington Consensus templates; Korea is a canonical case in economics curricula.',
    globalTextKo:
      '발전국가 문헌은 워싱턴 합의형 템플릿과 신용 배분·산업정책을 대비하며, 한국은 경제학 교과에서 대표 사례로 다루어진다.',
    koreanText:
      '산업은행·정책금융·기획 재정 등 한국식 국가 주도 성장의 유산(구체 수치·평가는 KDI·OECD·학술 문헌 확인).',
    agendaTags: ['World Bank', 'IMF'],
    relatedKeywords: [
      'developmental state',
      'industrial policy',
      'policy lending',
      'chaebol',
      'dirigisme',
      'Washington Consensus',
      'Korea model',
      '산업정책',
      '정책금융',
      '산업은행',
      '개발국가',
    ],
    globalSource: 'https://www.worldbank.org/en/topic/poverty/brief/world-development-report-1997-the-state-in-a-changing-world',
    koreanSource: 'https://www.kdi.re.kr/',
    koreanSourceLabelKo: '한국개발연구원(KDI)',
    date: '1960–1990 industrialization → 2020+ ongoing debate',
    similarityHint: 'model country framing',
    sourceVerified: true,
  },
  {
    id: 'matrix-1',
    topic: 'Networked Global Governance Matrix',
    globalText:
      "James P. Kelly III argues that a 'matrix' of ten interconnected human-rights governance networks lets the UN influence economic and social policy worldwide without formal treaties or direct democratic consent from member states.",
    globalTextKo:
      'James P. Kelly III에 따르면, 열 개의 상호 연결된 인권 거버넌스 네트워크로 이루어진 ‘매트릭스’를 통해 유엔은 회원국으로부터 형식상 조약이나 직접적 민주적 동의 없이도 전 세계 경제·사회 정책에 영향을 미칠 수 있다는 분석이다.',
    koreanText:
      '[Kelly 매트릭스 — 10개 네트워크] ① 옹호 ② 연구 ③ 정책 ④ 표준설정 ⑤ 해석 ⑥ 설명 ⑦ 이행 ⑧ 평가 ⑨ 집행 ⑩ 자금. 연성법·권고·가이드라인이 국내 정책·재판으로 흡수되는 통로. 한국 근거는 /matrix에서 네트워크별 증거·출처(하이라이트)로 정리.',
    agendaTags: [
      'Advocacy networks',
      'Research networks',
      'Policy networks',
      'Standards-setting networks',
      'Interpretive networks',
      'Explanatory networks',
      'Implementation networks',
      'Assessment networks',
      'Enforcement networks',
      'Funding networks',
    ],
    relatedKeywords: [
      'networked governance',
      'soft law',
      'GCR',
      'UNHCR guidelines',
      'judicialization',
      'transnational networks',
      'democratic bypass',
      'matrix of governance',
      'Global Compact on Refugees',
      'Kelly',
      'James P. Kelly',
      'human rights governance networks',
      'UN Global Compact',
      'treaty bypass',
      'norm diffusion',
      '네트워크 거버넌스',
      '연성법',
      '사법화',
      '인권 거버넌스',
    ],
    searchAliases: ['Soros funding', 'EU globalists'],
    globalSource:
      'https://fedsoc.org/commentary/publications/the-matrix-of-human-rights-governance-networks',
    koreanSource: 'https://www.globaldetentionproject.org/countries/asia-pacific/south-korea',
    koreanSourceLabelKo: 'GDP · 한국 이주구금 프로필(정렬 참고)',
    date: '2008 Kelly framework → ongoing norm diffusion',
    similarityHint: 'governance architecture',
    sourceVerified: false,
  },
];
